FROM golang:1.22.5

WORKDIR /app

# Install Air for live reload
RUN go install github.com/cosmtrek/air@v1.51.0

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the source code
COPY . .

# Expose port for the application
EXPOSE ${API_HTTP_PORT}

# Command to run when the container starts
CMD ["sh", "-c", "air -c .air.toml"]
