FROM golang:1.22.5

WORKDIR /app

# Install Air for live reload
RUN go install github.com/cosmtrek/air@v1.51.0

# Install Delve debugger
RUN go install github.com/go-delve/delve/cmd/dlv@latest

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the source code
COPY . .

# Expose ports for the application and debugger
EXPOSE ${API_HTTP_PORT} 2345

# Create a shell script to choose between Air and Delve
RUN echo '#!/bin/sh' > /start.sh && \
    echo 'if [ "$DEBUG" = "true" ]; then' >> /start.sh && \
    echo '    dlv debug --headless --listen=:2345 --api-version=2 --accept-multiclient --continue ./src/main.go' >> /start.sh && \
    echo 'else' >> /start.sh && \
    echo '    air -c .air.toml' >> /start.sh && \
    echo 'fi' >> /start.sh && \
    chmod +x /start.sh

# Use the shell script as the entry point
CMD ["/start.sh"]